export default {

    updateFlags: [],
    firstState: "firstState"
    , topicDetails: {},
    me: {},
    groupedKeyWords: {},
    meKeywords: [],
    tree: [],
    treeName: '',
    topics: [
        { name: "Development", active: false, keywords: [] },
        { name: "Services", active: false, keywords: [] },
        { name: "Security", active: false }, //Borders and security
        { name: "Budget", active: false },
        { name: "Business and industry", active: false },
        { name: "Climate action", active: false },
        { name: "Competition", active: false },
        { name: "Consumers", active: false },
        { name: "Culture and media", active: false },
        // { name: "Customs", active: false },
        { name: "Digital economy and society", active: false },
        { name: "Economy, finance and the euro", active: false },
        { name: "Education and training", active: false },
        { name: "Employment and social affairs", active: false },
        { name: "Energy", active: false },
        { name: "Engineering", active: false }, //NEW!!
        { name: "Environment", active: false },
        { name: "Food safety", active: false },
        { name: "Foreign affairs and security policy", active: false },
        { name: "Fraud prevention", active: false },
        { name: "Home affairs", active: false },
        { name: "Humanitarian aid and civil protection", active: false },
        { name: "Institutional affairs", active: false },
        { name: "International cooperation and development", active: false },
        { name: "Justice and fundamental rights", active: false },
        { name: "Maritime affairs and fisheries", active: false },
        { name: "Migration and asylum", active: false },
        { name: "Public health", active: false },
        { name: "Regional policy", active: false },
        { name: "Research and innovation", active: false },
        { name: "Single market", active: false },
        { name: "Society", active: false },
        { name: "Sport", active: false },
        { name: "Statistics", active: false },
        { name: "Taxation", active: false },
        { name: "Trade", active: false },
        { name: "Transport", active: false },
        { name: "Youth", active: false }
    ]
}